# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "astropy"
          - "astroquery"
          - "channels-redis"
          - "channels[daphne]"
          - "click"
          - "django"
          - "django-cors-headers"
          - "django-dramatiq"
          - "djangorestframework"
          - "dramatiq-abort"
          - "dramatiq[redis,watch]"
          - "gpp-client"
          - "marshmallow"
          - "marshmallow-jsonapi"
          - "numpydoc"
          - "tom-tns"
          - "tomtoolkit"
      development-dependencies:
        patterns:
          - "pytest*"
          - "factory-boy"
          - "ruff"
          - "towncrier"
      documentation-dependencies:
        patterns:
          - "furo"
          - "sphinx*"
      notebook-dependencies:
        patterns:
          - "ipykernel"
    ignore:
      # TOMToolkit limit.
      - dependency-name: "django"
        versions: [">=5.0.0"]
      # ANTARES client workaround.
      - dependency-name: "marshmallow"
        versions: [">=4.0.0"]
      # TOMToolkit limit.
      - dependency-name: "astropy"
        versions: [">=7.0.0"]
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ci-dependencies:
        patterns:
          - "*"
