exclude: ^(docs/|js_tests/|src/goats_tom/static/|src/goats_tom/templates/|LICENSE)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-docstring-first
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: detect-private-key
      - id: forbid-submodules
      - id: no-commit-to-branch
        args:
          - --branch=main
      - id: name-tests-test
        args:
          - --pytest-test-first
        exclude: ^(src/goats_tom/tests/|tests/data/)
      - id: pretty-format-json
        args:
          - --autofix

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.12"
    hooks:
      - id: ruff-check
        args: [--fix]
        exclude: ^(docs/|js_tests/|src/goats_tom/brokers/|src/goats_tom/migrations/)
      - id: ruff-format
        exclude: ^(docs/|js_tests/|src/goats_tom/brokers/|src/goats_tom/migrations/)

  # - repo: https://github.com/numpy/numpydoc
  #   rev: "v1.8.0"
  #   hooks:
  #     - id: numpydoc-validation
  #       exclude: ^(tests/)

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.15
    hooks:
      - id: uv-lock
