# Environment configuration for GOATS

# For ARM (M1/M2) Mac users:
#  - Ensure you have Rosetta 2 installed to run Intel-based binaries.
#  - Install an x86 version of Anaconda or Miniconda.
#  - You need to switch to an x86 terminal for installing and running
#    Intel-only packages like DRAGONS.

# See documentation for more help:
# https://goats.readthedocs.io/en/latest/

# Creating the environment:
# conda env create -f environment.yml

name: goats

channels:
  - conda-forge
  - http://astroconda.gemini.edu/public
  - nodefaults

dependencies:
  - dragons=3.2.3
  - python-confluent-kafka=1.7.0  # Required for linking librdkafka in conda.
  - librdkafka>=1.7.0  # Required while antares-client upgrades kafka.
  - pip
  - python>=3.10
  - redis-server
  # - astro-datalab

  # For development, use clone the GOATS repo and "pip install -e ." or
  # for tests, install with "pip install -e '.[test]'".

  # Uncomment the below lines to install from GitHub (requires repo access).
  - pip:
    - git+https://github.com/gemini-hlsw/goats.git@25.2.1