# Environment configuration for GOATS

# For ARM (M1/M2) Mac users:
#  - Ensure you have Rosetta 2 installed to run Intel-based binaries.
#  - Install an x86 version of Anaconda or Miniconda.
#  - You need to switch to an x86 terminal for installing and running
#    Intel-only packages like DRAGONS.

# See documentation for more help:
# https://goats.readthedocs.io/en/latest/

# Creating the environment:
# conda env create -f environment.yml

name: goats

channels:
  - conda-forge
  - http://astroconda.gemini.edu/public
  - nodefaults

dependencies:
  - dragons=4.0.0
  - pip=25.1.1
  - python=3.12
  - redis-server=7.2.8
  - pip:
    - git+https://github.com/gemini-hlsw/goats.git@25.6.0rc2