[project]
name = "goats"
description = "Gemini Observation and Analysis of Targets System."
readme = "README.md"
authors = [
    {name="GOATS Team"},
]
classifiers = [
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Astronomy",
]
requires-python = ">=3.10.0"
dependencies = [
    "tom-antares",
    "tom-gemini-community",
    "tomtoolkit>=2.14",
    "click",
]
version = "0.0.1"

[project.urls]
"Homepage" = "https://github.com/gemini-hlsw/goats"

[project.optional-dependencies]
test = [
    "pytest",
    "flake8",
    "pytest-xdist",
    "pytest-cov",
]

[project.scripts]
goats = "goats.cli:cli"

[tool.pytest.ini_options]
testpaths = ["tests/unit"]

[tool.towncrier]
    version = ""
    package_dir = "goats"
    filename = "CHANGES.md"
    directory = "doc/changes"
    start_string = "<!-- towncrier release notes start -->\n"
    underlines = ["", "", ""]
    title_format = "## GOATS {version} ({project_date})"
    issue_format = "[[#{issue}](https://noirlab.atlassian.net/browse/{issue})]"
    template = "doc/changes/template.jinja"
    [[tool.towncrier.type]]
        directory = "new"
        name = "New Features"
        showcontent = true
    [[tool.towncrier.type]]
        directory = "change"
        name = "Changes"
        showcontent = true
    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bug Fixes"
        showcontent = true
    [[tool.towncrier.type]]
        directory = "perf"
        name = "Enhancements"
        showcontent = true
    [[tool.towncrier.type]]
        directory = "other"
        name = "Other"
        showcontent = true