# Generated by Django 5.2.17 on 2026-09-24 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goats_tom", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TNSGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("allow_join_requests", models.BooleanField(default=False)),
                ("recommended_authors", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tns_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TNS group",
                "verbose_name_plural": "TNS groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TNSGroupJoinRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tns_join_requests_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tns_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tns_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="goats_tom.tnsgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "TNS group join request",
                "verbose_name_plural": "TNS group join requests",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TNSGroupMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tns_memberships_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tns_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="goats_tom.tnsgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tns_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TNS group membership",
                "verbose_name_plural": "TNS group memberships",
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="TNSSubmissionRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                (
                    "group_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("bot_id", models.CharField(blank=True, default="", max_length=50)),
                (
                    "target_pk",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "object_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("report", "Discovery report"),
                            ("classify", "Classification"),
                        ],
                        max_length=16,
                    ),
                ),
                ("succeeded", models.BooleanField(default=False)),
                ("iau_name", models.CharField(blank=True, default="", max_length=100)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tns_submissions_via_my_bot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tns_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tns_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="goats_tom.tnsgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "TNS submission record",
                "verbose_name_plural": "TNS submission records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="tnsgroup",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_tns_group_per_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="tnsgroupjoinrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("requester", "tns_group"),
                name="unique_pending_tns_join_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="tnsgroupmembership",
            constraint=models.UniqueConstraint(
                fields=("tns_group", "user"),
                name="unique_tns_membership_per_group_and_user",
            ),
        ),
    ]
