# Generated by Django 4.2.25 on 2025-12-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragonsrecipe',
            name='additional_files',
            field=models.TextField(blank=True, help_text='Additional FITS files to pass to reduce_data(files=...), stored as a list of paths relative to the target directory.', null=True),
        ),
        migrations.AlterField(
            model_name='dragonsrecipe',
            name='ucals',
            field=models.TextField(blank=True, help_text='Calibration overrides passed to reduce_data(ucals=...), stored as a mapping of calibration type to file path.', null=True),
        ),
    ]
