# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntaresLocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locus_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('latest_alert_id', models.CharField(max_length=128)),
                ('latest_alert_mjd', models.FloatField(blank=True, null=True)),
                ('alert_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'ANTARES loci',
                'ordering': ['-last_updated'],
            },
        ),
    ]
