# Generated by Django 5.2.16 on 2026-07-31 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('goats_tom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntaresKafkaLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=128)),
                ('api_secret', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AntaresPIGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antares_pi_group', to='auth.group')),
                ('pi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antares_pi_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ANTARES PI group',
                'verbose_name_plural': 'ANTARES PI groups',
            },
        ),
        migrations.CreateModel(
            name='AntaresStreamSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.JSONField(default=list)),
                ('consumer_group', models.CharField(blank=True, default='', help_text="Optional. Appended to an automatically-generated, per-subscription consumer group name; leave blank to use that generated name on its own. Set a new value to force a full replay from the earliest available message on the subscribed topics, which is what a brand-new consumer group name does. Note this is a suffix, not the whole name: the generated prefix is always applied, so your consumer group can never collide with another user's.", max_length=128)),
                ('save_all_targets', models.BooleanField(default=False)),
                ('trigger_gemini_observations', models.BooleanField(default=False)),
                ('handler_code', models.TextField(blank=True, default='', help_text="Optional user-defined function named 'myfilter(locus)' run against each locus before it's saved. Return True to keep the locus, False to skip it. See goats_tom.antares_locus_handler for the execution model and its restrictions.")),
                ('dramatiq_message_id', models.CharField(blank=True, max_length=64, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('last_handler_warning', models.TextField(blank=True, default='')),
                ('last_handler_warning_at', models.DateTimeField(blank=True, null=True)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_topics', models.TextField(blank=True, default='')),
                ('draft_consumer_group', models.CharField(blank=True, default='', max_length=128)),
                ('draft_save_all_targets', models.BooleanField(default=False)),
                ('draft_trigger_gemini_observations', models.BooleanField(default=False)),
                ('draft_handler_code', models.TextField(blank=True, default='')),
                ('draft_error', models.TextField(blank=True, default='')),
                ('draft_error_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antares_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ANTARES stream subscription',
                'verbose_name_plural': 'ANTARES stream subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PersonalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_group', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'personal group',
                'verbose_name_plural': 'personal groups',
            },
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registration request',
                'verbose_name_plural': 'registration requests',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RSPTapLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AntaresGroupJoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', max_length=16)),
                ('requested_view_dashboard', models.BooleanField(default=True)),
                ('requested_save_targets', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antares_join_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antares_join_requests', to=settings.AUTH_USER_MODEL)),
                ('pi_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='goats_tom.antarespigroup')),
            ],
            options={
                'verbose_name': 'ANTARES group join request',
                'verbose_name_plural': 'ANTARES group join requests',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('requester', 'pi_group'), name='unique_pending_join_request')],
            },
        ),
        migrations.CreateModel(
            name='AntaresDashboardMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_dashboard', models.BooleanField(default=True)),
                ('can_save_targets', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antares_memberships_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antares_dashboard_memberships', to=settings.AUTH_USER_MODEL)),
                ('pi_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='goats_tom.antarespigroup')),
            ],
            options={
                'verbose_name': 'ANTARES dashboard membership',
                'verbose_name_plural': 'ANTARES dashboard memberships',
                'constraints': [models.UniqueConstraint(fields=('pi_group', 'user'), name='unique_membership_per_group_and_user')],
            },
        ),
        migrations.CreateModel(
            name='AntaresLocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locus_id', models.CharField(db_index=True, max_length=64)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('latest_alert_id', models.CharField(max_length=128)),
                ('latest_alert_mjd', models.FloatField(blank=True, null=True)),
                ('latest_alert_magnitude', models.FloatField(blank=True, null=True)),
                ('latest_alert_topic', models.CharField(blank=True, db_index=True, default='', max_length=256)),
                ('in_tns', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loci', to='goats_tom.antaresstreamsubscription')),
            ],
            options={
                'verbose_name_plural': 'ANTARES loci',
                'ordering': ['-last_updated'],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'locus_id'), name='unique_locus_per_subscription')],
            },
        ),
        migrations.CreateModel(
            name='AntaresTargetSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locus_id', models.CharField(db_index=True, max_length=64)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antares_target_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ANTARES target save',
                'verbose_name_plural': 'ANTARES target saves',
                'ordering': ['saved_at'],
                'constraints': [models.UniqueConstraint(fields=('locus_id', 'saved_by'), name='unique_target_save_per_locus_and_user')],
            },
        ),
    ]
