# Generated by Django 5.2.16 on 2026-07-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('goats_tom', '0002_antares_stream_and_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='requested_groups',
            field=models.ManyToManyField(blank=True, related_name='registration_requests', to='auth.group'),
        ),
    ]
