# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0002_antareslocus'),
    ]

    operations = [
        migrations.AddField(
            model_name='antareslocus',
            name='latest_alert_magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antareslocus',
            name='in_tns',
            field=models.BooleanField(default=False),
        ),
    ]
