# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0003_antareslocus_magnitude_tns'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntaresStreamSubscription',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('topics', models.JSONField(default=list)),
                ('save_all_targets', models.BooleanField(default=False)),
                (
                    'dramatiq_message_id',
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ('is_running', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ANTARES stream subscription',
                'verbose_name_plural': 'ANTARES stream subscriptions',
            },
        ),
    ]
