# Generated by Django 5.2.17 on 2026-10-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0003_remove_tnslogin_group_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnsgroupjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=16),
        ),
    ]
