# Generated by Django 5.2.17 on 2026-10-09 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('goats_tom', '0004_tns_join_request_revoked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('detail', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('subject_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_pending', models.BooleanField(default=False)),
                ('email_attempts', models.PositiveSmallIntegerField(default=0)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_caused', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('subject_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='goats_tom_n_recipie_adb8f3_idx'), models.Index(fields=['subject_type', 'subject_id'], name='goats_tom_n_subject_3c1117_idx'), models.Index(condition=models.Q(('email_pending', True), ('emailed_at__isnull', True)), fields=['created_at'], name='notification_email_due_idx')],
            },
        ),
    ]
