# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0004_antaresstreamsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='handler_code',
            field=models.TextField(
                blank=True,
                default='',
                help_text=(
                    'Optional user-defined function body run against each '
                    'locus before it\'s saved. Set a local variable `keep` '
                    'to True/False to control whether the locus is kept. '
                    'See goats_tom.antares_locus_handler for the execution '
                    'model and its restrictions.'
                ),
            ),
        ),
    ]
