# Generated by Django 5.2.16 on 2026-08-05 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0004_login_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='gpp_observation_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='gpp_program_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='max_triggers',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Maximum number of Gemini observations this subscription may create in total. Leave blank for no limit.', null=True),
        ),
        migrations.CreateModel(
            name='GeminiTriggerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locus_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16)),
                ('gpp_observation_id', models.CharField(blank=True, default='', max_length=128)),
                ('gpp_target_id', models.CharField(blank=True, default='', max_length=128)),
                ('execution_time_hours', models.FloatField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemini_triggers', to='goats_tom.antaresstreamsubscription')),
            ],
            options={
                'verbose_name': 'Gemini trigger record',
                'verbose_name_plural': 'Gemini trigger records',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'locus_id'), name='unique_gemini_trigger_per_locus')],
            },
        ),
    ]
