# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0005_antaresstreamsubscription_handler_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='trigger_gemini_observations',
            field=models.BooleanField(default=False),
        ),
    ]
