# Generated by Django 5.2.16 on 2026-08-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0005_gemini_triggering'),
    ]

    operations = [
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='gpp_observation_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
