# Generated by Django 5.2.16 on 2026-08-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0006_template_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='antareslocus',
            name='latest_alert_passband',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
