# Generated by Django 4.2.25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goats_tom', '0006_antaresstreamsubscription_trigger_gemini'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntaresKafkaLogin',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('api_key', models.CharField(max_length=128)),
                ('api_secret', models.CharField(max_length=128)),
                ('group', models.CharField(blank=True, default='', max_length=128)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='antareskafkalogin',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
