# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0007_antareskafkalogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='last_handler_warning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='last_handler_warning_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
