# Generated by Django 5.2.16 on 2026-08-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0007_locus_passband'),
    ]

    operations = [
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='gpp_workflow_state',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
