# Generated by Django 5.2.17 on 2026-08-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0008_gpp_workflow_state'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='geminitriggerrecord',
            name='unique_gemini_trigger_per_locus',
        ),
        migrations.AddField(
            model_name='geminitriggerrecord',
            name='generation',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddConstraint(
            model_name='geminitriggerrecord',
            constraint=models.UniqueConstraint(fields=('subscription', 'generation', 'locus_id'), name='unique_gemini_trigger_per_locus_per_run'),
        ),
    ]
