# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0008_antaresstreamsubscription_handler_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antaresstreamsubscription',
            name='handler_code',
            field=models.TextField(
                blank=True,
                default='',
                help_text=(
                    "Optional user-defined function named 'myfilter(locus)' "
                    'run against each locus before it\'s saved. Return True '
                    'to keep the locus, False to skip it. See '
                    'goats_tom.antares_locus_handler for the execution '
                    'model and its restrictions.'
                ),
            ),
        ),
    ]
