# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0009_antaresstreamsubscription_handler_code_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antareskafkalogin',
            name='group',
        ),
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='group',
            field=models.CharField(
                blank=True,
                default='',
                help_text=(
                    'Optional. If left blank, a built-in default group '
                    'name is used. Set this explicitly rather than '
                    "relying on the underlying client's own default "
                    "(which falls back to the machine's hostname), so "
                    'the consumer group -- and therefore offset tracking '
                    '-- stays stable across restarts and across hosts. '
                    'Use a brand-new group name to force a full replay '
                    'from the earliest available message on the '
                    'subscribed topics.'
                ),
                max_length=128,
            ),
        ),
    ]
