# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0010_move_group_to_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='generation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
