# Generated by Django 5.2.17 on 2026-08-08 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0010_run_scope_and_template_target'),
        ('tom_observations', '0016_alter_facility_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminitriggerrecord',
            name='observation_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tom_observations.observationrecord'),
        ),
    ]
