# Generated by Django 5.2.17 on 2026-08-20 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0011_trigger_observation_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrodatalablogin',
            name='jupyter_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='RemoteJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField(default=0)),
                ('run_number', models.PositiveIntegerField(db_index=True, default=0)),
                ('datalab_username', models.CharField(max_length=128)),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('kernel_id', models.CharField(blank=True, max_length=64, null=True)),
                ('remote_pid', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed'), ('lost', 'Lost')], db_index=True, default='pending', max_length=16)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('restart_count', models.PositiveIntegerField(default=0)),
                ('loci_seen', models.PositiveIntegerField(default=0)),
                ('loci_kept', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('launched_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_jobs', to='goats_tom.antaresstreamsubscription')),
            ],
            options={
                'verbose_name': 'remote job',
                'verbose_name_plural': 'remote jobs',
                'ordering': ['-launched_at'],
                'indexes': [models.Index(fields=['status', 'last_heartbeat'], name='remotejob_status_heartbeat'), models.Index(fields=['subscription', '-launched_at'], name='remotejob_sub_launched')],
            },
        ),
    ]
