# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0011_antaresstreamsubscription_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='draft_topics',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='draft_group',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='draft_save_all_targets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='draft_trigger_gemini_observations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='draft_handler_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='draft_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
