# Generated by Django 5.2.17 on 2026-08-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0012_astrodatalablogin_jupyter_token_remotejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='max_loci',
            field=models.PositiveIntegerField(blank=True, help_text='Stop ingesting once the dashboard holds this many loci. Blank for no limit.', null=True),
        ),
    ]
