# Generated by Django 5.2.17 on 2026-08-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0013_antaresstreamsubscription_max_loci'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotejob',
            name='remote_dir_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
