# Generated by Django 5.2.17 on 2026-08-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0014_remotejob_remote_dir_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed'), ('lost', 'Lost'), ('stopped', 'Stopped')], db_index=True, default='pending', max_length=16),
        ),
    ]
