# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0014_rsptaplogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='antareslocus',
            name='latest_alert_topic',
            field=models.CharField(
                blank=True, db_index=True, default='', max_length=256
            ),
        ),
    ]
