# Generated by Django 5.2.17 on 2026-08-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0015_alter_remotejob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='last_handler_warning_is_error',
            field=models.BooleanField(default=True),
        ),
    ]
