# Generated by Django 4.2.25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goats_tom', '0015_antareslocus_latest_alert_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antareslocus',
            name='alert_count',
        ),
        migrations.CreateModel(
            name='AntaresTargetSave',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'locus_id',
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                (
                    'saved_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='antares_target_saves',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
