# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0016_remove_alert_count_add_target_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='antaresstreamsubscription',
            name='draft_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
