"""Add `DataLabJob` for GOA downloads and DRAGONS reductions on Data Lab.

**One new table, nothing altered.** `RemoteJob` and the ANTARES stream are
untouched -- see *Keep ANTARES out of Phases 3 and 4* in ``STATUS.md`` for
why this is a separate model rather than a generalization of that one.

Reversing drops the table. Safe: nothing else references it, and no existing
row moves into or out of it.
"""

# Generated by Django 5.2.17 on 2026-09-02 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0017_encrypt_login_credentials'),
        ('tom_observations', '0016_alter_facility_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLabJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('download', 'GOA download'), ('reduction', 'DRAGONS reduction')], db_index=True, max_length=16)),
                ('datalab_username', models.CharField(max_length=128)),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('kernel_id', models.CharField(blank=True, max_length=64, null=True)),
                ('remote_pid', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed'), ('lost', 'Lost')], db_index=True, default='pending', max_length=16)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('files_seen', models.PositiveIntegerField(default=0)),
                ('files_kept', models.PositiveIntegerField(default=0)),
                ('log_offset', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('remote_dir_deleted', models.BooleanField(default=False)),
                ('launched_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dragons_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datalab_jobs', to='goats_tom.dragonsrun')),
                ('observation_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datalab_jobs', to='tom_observations.observationrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Lab job',
                'verbose_name_plural': 'Data Lab jobs',
                'ordering': ['-launched_at'],
                'indexes': [models.Index(fields=['status', 'last_heartbeat'], name='datalabjob_status_heartbeat')],
            },
        ),
    ]
