# Generated by Django 5.2.17 on 2026-09-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats_tom', '0018_datalabjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragonsrun',
            name='output_written_at',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
