name: Run JS Tests
on:
  pull_request:
    paths:
      - "src/goats_tom/static/js/**/*.js"
      - "js_tests/**/*.js"
      - ".github/workflows/run_js_tests.yaml"

  push:
    branches:
      - main

jobs:
  run_js_tests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: latest

    - name: Install JS dependencies
      run: npm install

    - name: Run JS tests
      run: npm test
