name: Run Tests
on:
  push:
    paths:
      - "src/**/*.py"
      - "tests/unit/**/*.py"

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: goats

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install confluent-kafka dependencies
        run: sudo apt-get update && sudo apt-get install -y librdkafka-dev

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Build and install
        run: |
          cd ${{ github.workspace }}/goats
          pip install -v -e ".[test]"

      - name: Run tests and calculate coverage
        run: |
          cd ${{ github.workspace }}/goats
          pytest -r A -v -n auto --cov=goats --cov-report=term --cov=tests --cov-branch
