name: Run Tests

on:
  pull_request:
    paths:
      - "src/**/*.py"
      - "tests/unit/**/*.py"
      - "pyproject.toml"
      - "uv.lock"
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --dev --group github

      - name: Run tests and calculate coverage
        run: |
          uv run pytest -r A -v -n auto --cov=src --cov-report=xml --cov=tests --cov-branch

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
